/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador_synth.v:6" *)
module contador_synth(push, clk, cuenta);
  (* src = "contador_synth.v:13" *)
  wire [2:0] _00_;
  (* src = "contador_synth.v:15" *)
  (* unused_bits = "3" *)
  wire [31:0] _01_;
  (* src = "contador_synth.v:15|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _02_;
  (* src = "contador_synth.v:8" *)
  input clk;
  (* init = 3'h0 *)
  (* src = "contador_synth.v:9" *)
  output [2:0] cuenta;
  reg [2:0] cuenta = 3'h0;
  (* src = "contador_synth.v:7" *)
  input push;
  assign _00_[0] = push ? (* src = "contador_synth.v:15" *) _01_[0] : cuenta[0];
  assign _00_[1] = push ? (* src = "contador_synth.v:15" *) _01_[1] : cuenta[1];
  assign _00_[2] = push ? (* src = "contador_synth.v:15" *) _01_[2] : cuenta[2];
  (* src = "contador_synth.v:13" *)
  always @(posedge clk)
      cuenta[0] <= _00_[0];
  (* src = "contador_synth.v:13" *)
  always @(posedge clk)
      cuenta[1] <= _00_[1];
  (* src = "contador_synth.v:13" *)
  always @(posedge clk)
      cuenta[2] <= _00_[2];
  assign _01_[0] = cuenta[0] ^(* src = "contador_synth.v:15|<techmap.v>:262" *)  1'h1;
  assign _02_[1] = cuenta[1] &(* src = "contador_synth.v:15|<techmap.v>:260|<techmap.v>:221" *)  cuenta[0];
  assign _01_[1] = cuenta[1] ^(* src = "contador_synth.v:15|<techmap.v>:263" *)  cuenta[0];
  assign _01_[2] = cuenta[2] ^(* src = "contador_synth.v:15|<techmap.v>:263" *)  _02_[1];
  assign _01_[31:4] = 28'h0000000;
  assign { _02_[31:2], _02_[0] } = { 29'h00000000, _01_[3], cuenta[0] };
endmodule
